### PR TITLE
Add SqlServer Instance Discovery

### LINKED ISSUE #57: Add SQL Server Discovery
App should be able to interact with multiple instances of SQL Server without the need to modify a configuration file. 

https://github.com/MonitoringSolutionsInc/DatabaseBackupTool/blob/06c45798dc67748daa257623c20c0ae3e0abceda/DatabaseBackupTool/SqlConnectorData.xml

### PR DESCRIPTION
**Pull request by SamuraiTheNinja**
closes #57 

This will assume the default sqlServer instance (as defined in the XML still) but will load other Sql Server Instances in the background and update the drop down with more options when they become available. Selecting another item from the dropdown will update the name of the instance to use. Note the username, password, and IntialCatalog are unchanged from what is loaded in from the XML on start

### CODE REVIEW

**Comment by SamuraiTheNinja** [comment]
This failed on Chris's machine (where there are 2 sql server instances). He had found another algorithm that supposedly does the same thing

**Comment by JazzGlobal** [comment]
> This failed on Chris's machine (where there are 2 sql server instances). He had found another algorithm that supposedly does the same thing

This is the link to the implementation of the alternate method. It is the first answer.: 

https://stackoverflow.com/questions/15967817/smoapplication-enumavailablesqlservers-does-not-retrieve-local-server-instances/54337185

**Review by JazzGlobal — CHANGES_REQUESTED** [review]
See  below

https://github.com/MonitoringSolutionsInc/DatabaseBackupTool/pull/60#issuecomment-917186617

**Comment by SamuraiTheNinja** [comment]
Forgot about your link to a solution. Ended up finding a different one pretty quickly, It seems to work  on my end (with only 1 instance)

**Review by JazzGlobal — CHANGES_REQUESTED** [review]
Not working as expected. I have two SQL Server instances (configured the same, besides the name) on my computer. The program fails to see either and encounters an unhandled exception of ArgumentOutOfRange. 

image

**Review by JazzGlobal — CHANGES_REQUESTED** [review]
Same error as before. Not sure why this isn't working. Perhaps testing should be performed on SOFTWARE-TEST to rule out the possibility of misconfigured hardware.

**Comment by JazzGlobal** [comment]
@SamuraiTheNinja 
The SQL Instance discovery works on SOFTWARE-TEST but not my two PCs at my house. I'm sure it's just a configuration problem. Either way, we'll need error handling to ensure it does not crash on PCs where it doesn't properly discover instances. 

There is also a separate problem with this PR. Although it successfully finds the SQL instances (network and local) on SOFTWARE-TEST, you cannot actually access them. You can select them using the dropdown but it only displays the databases on the local SQLEXPRESS server.

**Review by JazzGlobal — APPROVED** [review]
Works as expected. Approved.

**Pull request merged**
